version: '3.8'
services:
  bot:
    build: .
    env_file:
      - .env
  ports:
    - "8080:8080" # Пробрасываем порт 8080 контейнера на порт 8080 хоста
    restart: unless-stopped
    networks:
      - botnet
    # limit memory usage
    mem_limit: 150m

networks:
  botnet:
    driver: bridge
