name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check SSH_HOST
        run: |
          if [ -z "${SSH_HOST}" ]; then
            echo "❌ SSH_HOST is empty"
            exit 1
          else
            echo "✅ SSH_HOST is set (length: ${#SSH_HOST})"
            echo "Second half: ${SSH_HOST:${#SSH_HOST}/2}"
          fi
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Check SSH_USER
        run: |
          if [ -z "${SSH_USER}" ]; then
            echo "❌ SSH_USER is empty"
            exit 1
          else
            echo "✅ SSH_USER is set (length: ${#SSH_USER})"
            echo "Second half: ${SSH_USER:${#SSH_USER}/2}"
          fi
        env:
          SSH_USER: ${{ secrets.SSH_USER }}

      - name: Check WORK_DIR
        run: |
          if [ -z "${WORK_DIR}" ]; then
            echo "❌ WORK_DIR is empty"
            exit 1
          else
            echo "✅ WORK_DIR is set (length: ${#WORK_DIR})"
            echo "Second half: ${WORK_DIR:${#WORK_DIR}/2}"
          fi
        env:
          WORK_DIR: ${{ secrets.WORK_DIR }}

      - name: Check SSH_PRIVATE_KEY length
        run: |
          if [ -z "${SSH_PRIVATE_KEY}" ]; then
            echo "❌ SSH_PRIVATE_KEY is empty"
            exit 1
          else
            echo "✅ SSH_PRIVATE_KEY is set (length: ${#SSH_PRIVATE_KEY})"
          fi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}



          
