name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image_name: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Используем имя репозитория для имени образа.
          # `metadata-action` автоматически приведет имя владельца к нижнему регистру.
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    # Явно определяем переменные окружения из секретов для наглядности.
    # Задача завершится с более понятной ошибкой, если эти секреты не установлены.
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      WORK_DIR: ${{ secrets.WORK_DIR }}
      IMAGE_NAME: ${{ needs.build-and-push-image.outputs.image_name }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: Add server fingerprint to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.WORK_DIR }}

            # Устанавливаем переменную окружения с точным именем образа из шага сборки
            export BOT_IMAGE="${{ env.IMAGE_NAME }}"
            echo "Attempting to deploy image: $BOT_IMAGE"

            # Безопасно обновляем .env файл на сервере, добавляя/обновляя BOT_TOKEN
            # Это позволяет хранить токен в GitHub Secrets, а не в репозитории или на диске сервера.
            if [ -f .env ]; then
                grep -v '^BOT_TOKEN=' .env > .env.tmp && mv .env.tmp .env
            fi
            echo "BOT_TOKEN=${{ env.BOT_TOKEN }}" >> .env

            # Логинимся в GitHub Container Registry
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Скачиваем образ, используя переменную окружения, и перезапускаем сервис
            docker compose pull
            docker compose up -d --remove-orphans
            
            # Очищаем старые образы
            docker image prune -af

            echo "Deployment successful. Waiting a moment for the container to initialize..."
            sleep 5 # Даем контейнеру пару секунд на запуск и генерацию первых логов

            echo "Displaying recent logs from the container:"
            # Выводим последние 50 строк логов сервиса 'bot' для быстрой проверки.
            # Это поможет сразу увидеть, успешно ли стартовало приложение внутри контейнера.
            docker compose logs --tail 50 bot
